[package]
name = "shortest-word-path"
version = "0.1.0"
edition = "2021"
rust-version = "1.69.0"

[dependencies]
clap.workspace = true
dict-lib = { path = "../dict-lib" }
anyhow.workspace = true
log.workspace = true
simple_logger.workspace = true
