[workspace]
members = [
    "shortest-word-path",
    "dict"
]

[profile.release-lto]
inherits = "release"
lto = true

[workspace.dependencies]
clap = { version = "4", features = [ "derive" ] }
roaring = "0.10"
