[package]
name = "dict-lib"
version = "0.1.0"
edition = "2021"
rust-version = "1.69.0"

[dependencies]
roaring.workspace = true
prost.workspace = true
zstd.workspace = true
anyhow.workspace = true
itertools.workspace = true

[build-dependencies]
prost-build.workspace = true
